"""
Automated Test Generation Service for OverseeX
Converts agent execution traces into pytest-compatible test cases.
"""
import json
import re
from typing import List, Dict, Any, Optional
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class TestGenerator:
    """
    Generates pytest-compatible test cases from agent execution traces.
    
    The generator analyzes trace data to identify:
    - Input patterns and expected outputs
    - Tool/API call sequences
    - Success/failure conditions
    - Edge cases and error handling
    """
    
    def __init__(self):
        self.template_imports = """import pytest
from overseex import OverseeX, mock_tools
from unittest.mock import MagicMock, patch
"""
    
    def generate_tests_from_trace(
        self,
        trace_data: Dict[str, Any],
        agent_name: str,
        test_name: Optional[str] = None
    ) -> str:
        """
        Generate a pytest test case from a single trace.
        
        Args:
            trace_data: The trace JSON containing execution details
            agent_name: Name of the agent being tested
            test_name: Optional custom test name
            
        Returns:
            Python code for the test case
        """
        # Extract key information from trace
        input_data = trace_data.get("input", "")
        output_data = trace_data.get("output", "")
        status = trace_data.get("status", "success")
        tool_calls = self._extract_tool_calls(trace_data)
        duration_ms = trace_data.get("duration_ms", 0)
        metadata = trace_data.get("metadata", {})
        
        # Generate test name
        if not test_name:
            test_name = self._generate_test_name(input_data, status)
        
        # Build test code
        test_code = self._build_test_code(
            test_name=test_name,
            agent_name=agent_name,
            input_data=input_data,
            expected_output=output_data,
            status=status,
            tool_calls=tool_calls,
            duration_ms=duration_ms,
            metadata=metadata
        )
        
        return test_code
    
    def generate_test_suite_from_traces(
        self,
        traces: List[Dict[str, Any]],
        agent_name: str,
        suite_name: Optional[str] = None
    ) -> str:
        """
        Generate a complete test suite from multiple traces.
        
        Args:
            traces: List of trace data dictionaries
            agent_name: Name of the agent being tested
            suite_name: Optional name for the test suite
            
        Returns:
            Python code for the complete test suite
        """
        if not suite_name:
            suite_name = f"Test{self._sanitize_name(agent_name)}Suite"
        
        # Categorize traces
        success_traces = [t for t in traces if t.get("status") == "success"]
        failure_traces = [t for t in traces if t.get("status") in ["error", "failed"]]
        
        # Build test suite
        code_parts = [
            self.template_imports,
            "",
            f'"""',
            f"Auto-generated test suite for {agent_name}",
            f"Generated by OverseeX on {datetime.utcnow().isoformat()}",
            f"Based on {len(traces)} execution traces",
            f'"""',
            "",
            "",
            f"class {suite_name}:",
            f'    """Test suite for {agent_name}"""',
            "",
            "    @pytest.fixture",
            "    def agent(self):",
            '        """Initialize the agent for testing"""',
            f"        # TODO: Initialize your {agent_name} agent here",
            "        return MagicMock()",
            "",
        ]
        
        # Generate happy path tests
        for i, trace in enumerate(success_traces[:10]):  # Limit to 10 success tests
            test_code = self._build_class_test_method(
                test_name=f"test_success_case_{i + 1}",
                trace_data=trace,
                agent_name=agent_name
            )
            code_parts.append(test_code)
        
        # Generate error handling tests
        for i, trace in enumerate(failure_traces[:5]):  # Limit to 5 failure tests
            test_code = self._build_class_test_method(
                test_name=f"test_error_handling_{i + 1}",
                trace_data=trace,
                agent_name=agent_name
            )
            code_parts.append(test_code)
        
        # Generate edge case tests
        edge_cases = self._identify_edge_cases(traces)
        for i, trace in enumerate(edge_cases[:5]):
            test_code = self._build_class_test_method(
                test_name=f"test_edge_case_{i + 1}",
                trace_data=trace,
                agent_name=agent_name
            )
            code_parts.append(test_code)
        
        return "\n".join(code_parts)
    
    def _extract_tool_calls(self, trace_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Extract tool/API calls from trace data."""
        tool_calls = []
        
        # Check various trace formats
        if "tool_calls" in trace_data:
            tool_calls = trace_data["tool_calls"]
        elif "steps" in trace_data:
            for step in trace_data["steps"]:
                if step.get("type") == "tool_call":
                    tool_calls.append(step)
        elif "metadata" in trace_data:
            metadata = trace_data["metadata"]
            if "tool_calls" in metadata:
                tool_calls = metadata["tool_calls"]
        
        return tool_calls
    
    def _generate_test_name(self, input_data: str, status: str) -> str:
        """Generate a descriptive test name from input."""
        # Clean and truncate input for test name
        clean_input = re.sub(r'[^a-zA-Z0-9\s]', '', str(input_data)[:50])
        words = clean_input.lower().split()[:5]
        
        if status == "success":
            prefix = "test_"
        else:
            prefix = "test_error_"
        
        return prefix + "_".join(words) if words else f"{prefix}case"
    
    def _sanitize_name(self, name: str) -> str:
        """Sanitize a name for use in Python code."""
        # Remove non-alphanumeric characters and convert to PascalCase
        words = re.sub(r'[^a-zA-Z0-9\s]', '', name).split()
        return "".join(word.capitalize() for word in words)
    
    def _build_test_code(
        self,
        test_name: str,
        agent_name: str,
        input_data: str,
        expected_output: str,
        status: str,
        tool_calls: List[Dict[str, Any]],
        duration_ms: int,
        metadata: Dict[str, Any]
    ) -> str:
        """Build a standalone test function."""
        
        # Escape strings for Python code
        # Convert input/output to strings if they're dicts
        input_str = input_data if isinstance(input_data, str) else json.dumps(input_data)
        output_str = expected_output if isinstance(expected_output, str) else json.dumps(expected_output)
        
        input_escaped = json.dumps(input_str)
        output_escaped = json.dumps(output_str)
        
        code = f'''
@pytest.mark.agentguard
def {test_name}():
    """
    Auto-generated test from trace.
    Input: {input_str[:100]}{'...' if len(str(input_str)) > 100 else ''}
    Expected: {'Success' if status == 'success' else 'Error handling'}
    """
    with mock_tools() as mocks:
'''
        
        # Add tool mock setup
        if tool_calls:
            code += "        # Set up tool mocks based on trace\n"
            for i, call in enumerate(tool_calls):
                tool_name = call.get("tool", call.get("name", f"tool_{i}"))
                tool_response = call.get("response", call.get("output", "{}"))
                if isinstance(tool_response, dict):
                    tool_response = json.dumps(tool_response)
                code += f"        mocks['{tool_name}'].return_value = {json.dumps(tool_response)}\n"
            code += "\n"
        
        # Add test execution
        code += f'''        # Execute agent
        result = agent.run({input_escaped})
        
'''
        
        # Add assertions based on status
        if status == "success":
            code += f'''        # Assert success
        assert result is not None
        assert "error" not in str(result).lower()
'''
            # Add output assertion if specific output expected
            if expected_output and len(str(expected_output)) < 500:
                code += f'''        
        # Assert expected output pattern
        expected_keywords = {json.dumps(output_str.split()[:5] if isinstance(output_str, str) else [])}
        for keyword in expected_keywords:
            assert keyword.lower() in str(result).lower(), f"Expected '{{keyword}}' in result"
'''
        else:
            code += f'''        # Assert proper error handling
        # The agent should handle this gracefully
        assert result is not None or pytest.raises(Exception)
'''
        
        # Add tool call assertions
        if tool_calls:
            code += "\n        # Assert tool calls were made\n"
            for call in tool_calls:
                tool_name = call.get("tool", call.get("name", "unknown"))
                code += f"        assert mocks['{tool_name}'].called, \"Expected {tool_name} to be called\"\n"
        
        # Add performance assertion
        if duration_ms > 0:
            max_duration = max(duration_ms * 2, 5000)  # Allow 2x or min 5s
            code += f'''
        # Performance check (based on trace: {duration_ms}ms)
        # assert execution_time < {max_duration}, "Execution took too long"
'''
        
        return code
    
    def _build_class_test_method(
        self,
        test_name: str,
        trace_data: Dict[str, Any],
        agent_name: str
    ) -> str:
        """Build a test method for a test class."""
        input_data = trace_data.get("input", "")
        output_data = trace_data.get("output", "")
        status = trace_data.get("status", "success")
        tool_calls = self._extract_tool_calls(trace_data)
        
        input_escaped = json.dumps(input_data)
        
        code = f'''
    def {test_name}(self, agent):
        """
        Auto-generated from trace.
        Status: {status}
        """
        with mock_tools() as mocks:
'''
        
        # Add mock setup
        if tool_calls:
            for call in tool_calls[:5]:  # Limit mock setup
                tool_name = call.get("tool", call.get("name", "tool"))
                response = call.get("response", "{}")
                if isinstance(response, dict):
                    response = json.dumps(response)
                code += f"            mocks['{tool_name}'].return_value = {json.dumps(response)}\n"
        
        code += f'''
            result = agent.run({input_escaped})
'''
        
        if status == "success":
            code += '''
            assert result is not None
            assert "error" not in str(result).lower()
'''
        else:
            code += '''
            # Error case - should be handled gracefully
            assert True  # Adjust based on expected behavior
'''
        
        return code
    
    def _identify_edge_cases(self, traces: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Identify edge cases from traces based on patterns."""
        edge_cases = []
        
        for trace in traces:
            input_data = str(trace.get("input", ""))
            
            # Identify potential edge cases
            is_edge_case = False
            
            # Empty or very short input
            if len(input_data.strip()) < 5:
                is_edge_case = True
            
            # Very long input
            if len(input_data) > 1000:
                is_edge_case = True
            
            # Contains special characters
            if re.search(r'[<>{}|\\^~\[\]`]', input_data):
                is_edge_case = True
            
            # Unusual duration (very fast or very slow)
            duration = trace.get("duration_ms", 0)
            if duration < 10 or duration > 30000:
                is_edge_case = True
            
            # High token count
            if trace.get("metadata", {}).get("tokens_used", 0) > 4000:
                is_edge_case = True
            
            if is_edge_case:
                edge_cases.append(trace)
        
        return edge_cases
    
    def generate_regression_test(
        self,
        baseline_trace: Dict[str, Any],
        agent_name: str
    ) -> str:
        """
        Generate a regression test that compares against baseline behavior.
        """
        input_data = baseline_trace.get("input", "")
        baseline_output = baseline_trace.get("output", "")
        tool_calls = self._extract_tool_calls(baseline_trace)
        
        code = f'''
@pytest.mark.agentguard
@pytest.mark.regression
def test_regression_{self._generate_test_name(input_data, "success").replace("test_", "")}():
    """
    Regression test: Ensures behavior matches baseline.
    Baseline recorded: {baseline_trace.get("created_at", "unknown")}
    """
    input_data = {json.dumps(input_data)}
    
    with mock_tools() as mocks:
'''
        
        # Add tool mocks
        for call in tool_calls:
            tool_name = call.get("tool", call.get("name", "tool"))
            response = call.get("response", "{}")
            code += f"        mocks['{tool_name}'].return_value = {json.dumps(response)}\n"
        
        code += f'''
        result = agent.run(input_data)
        
        # Baseline comparison
        baseline_output = {json.dumps(baseline_output)}
        
        # Check structural similarity
        assert type(result) == type(baseline_output), "Output type changed"
        
        # Check key content is preserved
        if isinstance(baseline_output, str):
            # At least 50% of words should match
            baseline_words = set(baseline_output.lower().split())
            result_words = set(str(result).lower().split())
            overlap = len(baseline_words & result_words)
            assert overlap >= len(baseline_words) * 0.5, "Output diverged significantly from baseline"
        
        # Tool call sequence should match
'''
        
        for i, call in enumerate(tool_calls):
            tool_name = call.get("tool", call.get("name", "tool"))
            code += f"        assert mocks['{tool_name}'].called, \"Missing expected tool call: {tool_name}\"\n"
        
        return code


# Singleton instance
test_generator = TestGenerator()
