"""add_user_fields

Revision ID: f18fcdb5ea1e
Revises: add_performance_indexes
Create Date: 2026-01-23 17:45:36.327527+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18fcdb5ea1e'
down_revision: Union[str, None] = 'add_performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agents_org_id_created_at', table_name='agents')
    op.alter_column('health_checks', 'endpoint',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_index('ix_health_checks_agent_id_checked_at', table_name='health_checks')
    op.drop_index('ix_health_checks_status', table_name='health_checks')
    op.drop_index('ix_traces_agent_id_created_at', table_name='traces')
    op.drop_index('ix_traces_status', table_name='traces')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'full_name')
    op.create_index('ix_traces_status', 'traces', ['status'], unique=False)
    op.create_index('ix_traces_agent_id_created_at', 'traces', ['agent_id', 'created_at'], unique=False)
    op.create_index('ix_health_checks_status', 'health_checks', ['status'], unique=False)
    op.create_index('ix_health_checks_agent_id_checked_at', 'health_checks', ['agent_id', 'checked_at'], unique=False)
    op.alter_column('health_checks', 'endpoint',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_index('ix_agents_org_id_created_at', 'agents', ['org_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
